file:
  base-origin: ${FILE_BASE_ORIGIN:src/main/resources/static/origin}
  base-upload: ${FILE_BASE_UPLOAD:src/main/resources/static/upload}

spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 512KB  # 단일 파일 512KB
      max-request-size: 3MB # 전체 요청 3MB

  datasource:
    url: jdbc:mysql://localhost:3306/hanarodb
    username: hanaro
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET:please-change-this-very-long-secret-256bits}
  expire-seconds: ${JWT_EXPIRE_SECONDS:3600}

management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      probes.enabled: true

